package com.smartjmeter.report;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Structured performance report writer.
 *
 * <p>Previously produced a bare {@code <pre>} block containing the
 * analyser text. Now renders a self-contained HTML page with:</p>
 * <ul>
 *   <li>Header (test name, environment, application, run window).</li>
 *   <li>KPI cards (sample count, error rate, avg / p95 response time,
 *       throughput).</li>
 *   <li>Per-transaction table.</li>
 *   <li>Correlation summary (window count, event count).</li>
 *   <li>Observability metrics snapshot (series counts).</li>
 *   <li>LLM analysis panel rendered from markdown-lite (headings,
 *       bullets, numbered lists, bold, inline code).</li>
 * </ul>
 *
 * <p>The backwards-compatible {@link #generate(String)} entry point is
 * preserved for older callers and test code.</p>
 */
public class ReportGenerator {

    public static final String DEFAULT_REPORT_PATH = "Performance_Report.html";

    /* --------- Legacy entry points --------- */

    public java.nio.file.Path generate(String analysis) throws Exception {
        return generate(analysis, DEFAULT_REPORT_PATH);
    }

    public java.nio.file.Path generate(String analysis, String outputPath) throws Exception {
        Context ctx = new Context.Builder().llmAnalysis(analysis).build();
        return generate(ctx, outputPath);
    }

    /* --------- New rich entry point --------- */

    public java.nio.file.Path generate(Context ctx, String outputPath) throws Exception {
        String html = renderHtml(ctx);
        java.nio.file.Path target = java.nio.file.Path.of(outputPath);
        if (target.getParent() != null) {
            java.nio.file.Files.createDirectories(target.getParent());
        }
        java.nio.file.Files.writeString(target, html);
        return target;
    }

    /* --------- Rendering --------- */

    private String renderHtml(Context ctx) {
        StringBuilder sb = new StringBuilder(8192);
        sb.append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"/>")
          .append("<title>AI Performance Report</title>")
          .append("<style>").append(CSS).append("</style></head><body>");

        sb.append("<header class=\"hero\">")
          .append("<div class=\"tag\">Smart Observability AI</div>")
          .append("<h1>AI Performance Report</h1>")
          .append("<div class=\"meta\">");
        appendMeta(sb, "Test", ctx.testName);
        appendMeta(sb, "Environment", ctx.environment);
        appendMeta(sb, "Application", ctx.application);
        appendMeta(sb, "Started", formatTs(ctx.startMs));
        appendMeta(sb, "Stopped", formatTs(ctx.stopMs));
        appendMeta(sb, "Generated", formatTs(System.currentTimeMillis()));
        sb.append("</div></header>");

        renderKpis(sb, ctx);
        renderVerdictBadge(sb, ctx);
        renderHealthScores(sb, ctx);
        renderFindings(sb, ctx);
        renderCharts(sb, ctx);
        renderTransactionTable(sb, ctx);
        renderBaselineDiff(sb, ctx);
        renderCorrelation(sb, ctx);
        renderO11y(sb, ctx);
        renderCloudWatch(sb, ctx);
        renderExternalMetrics(sb, ctx);
        renderCapacityForecast(sb, ctx);
        renderBusinessImpact(sb, ctx);
        renderAnalysis(sb, ctx);
        renderAppendix(sb, ctx);

        sb.append("<footer>Generated by JMeter Smart Observability AI Plugin v2.0.3</footer>");
        sb.append("</body></html>");
        return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private void renderKpis(StringBuilder sb, Context ctx) {
        Map<String, Object> overall = (Map<String, Object>) ctx.aggregate.getOrDefault("overall", Map.of());
        long count = asLong(overall.get("count"), 0);
        long errors = asLong(overall.get("errors"), 0);
        double errorRate = count == 0 ? 0d : (double) errors / count;
        long avg = asLong(overall.get("rt_avg_ms"), 0);
        long p95 = asLong(overall.get("rt_p95_ms"), 0);
        long max = asLong(overall.get("rt_max_ms"), 0);
        double durationSec = (ctx.startMs > 0 && ctx.stopMs > ctx.startMs)
                ? (ctx.stopMs - ctx.startMs) / 1000d
                : 0d;
        double throughput = durationSec > 0 ? count / durationSec : 0d;

        sb.append("<section class=\"kpis\">");
        kpi(sb, "Samples", Long.toString(count), null);
        kpi(sb, "Errors", Long.toString(errors), errors > 0 ? "danger" : "ok");
        kpi(sb, "Error Rate", String.format("%.2f%%", errorRate * 100), errorRate > 0 ? "danger" : "ok");
        kpi(sb, "Avg RT", avg + " ms", null);
        kpi(sb, "P95 RT", p95 + " ms", p95 > 1000 ? "warn" : null);
        kpi(sb, "Max RT", max + " ms", null);
        kpi(sb, "Throughput", String.format("%.2f/s", throughput), null);
        sb.append("</section>");
    }

    @SuppressWarnings("unchecked")
    private void renderTransactionTable(StringBuilder sb, Context ctx) {
        Map<String, Object> per = (Map<String, Object>) ctx.aggregate.getOrDefault("per_transaction", Map.of());
        if (per.isEmpty()) return;
        sb.append("<section class=\"card\"><h2>Per-transaction Summary</h2>")
          .append("<table><thead><tr>")
          .append("<th>Transaction</th><th>Count</th><th>Errors</th><th>Error %</th>")
          .append("<th>Min</th><th>Avg</th><th>P95</th><th>Max</th>")
          .append("</tr></thead><tbody>");
        for (Map.Entry<String, Object> e : per.entrySet()) {
            Map<String, Object> row = (Map<String, Object>) e.getValue();
            long c = asLong(row.get("count"), 0);
            long er = asLong(row.get("errors"), 0);
            double erRate = c == 0 ? 0d : (double) er / c;
            String rowClass = er > 0 ? " class=\"row-danger\"" : "";
            sb.append("<tr").append(rowClass).append(">")
              .append("<td>").append(escape(e.getKey())).append("</td>")
              .append("<td>").append(c).append("</td>")
              .append("<td>").append(er).append("</td>")
              .append("<td>").append(String.format("%.2f%%", erRate * 100)).append("</td>")
              .append("<td>").append(asLong(row.get("rt_min_ms"), 0)).append(" ms</td>")
              .append("<td>").append(asLong(row.get("rt_avg_ms"), 0)).append(" ms</td>")
              .append("<td>").append(asLong(row.get("rt_p95_ms"), 0)).append(" ms</td>")
              .append("<td>").append(asLong(row.get("rt_max_ms"), 0)).append(" ms</td>")
              .append("</tr>");
        }
        sb.append("</tbody></table></section>");
    }

    @SuppressWarnings("unchecked")
    private void renderBaselineDiff(StringBuilder sb, Context ctx) {
        Map<String, Object> d = ctx.baselineDiff;
        if (d == null || d.isEmpty()) return;
        boolean has = Boolean.TRUE.equals(d.get("has_previous"));
        sb.append("<section class=\"card\"><h2>Baseline Diff</h2>");
        if (!has) {
            sb.append("<p class=\"muted\">No previous baseline found &mdash; this run will be saved as the new baseline.</p>")
              .append("</section>");
            return;
        }
        Object prevAt = d.get("previous_at");
        sb.append("<div class=\"pill-row\">")
          .append(pill("Previous run", prevAt == null ? "?" : prevAt.toString()))
          .append("</div>");

        List<String> notable = (List<String>) d.getOrDefault("notable", List.of());
        if (!notable.isEmpty()) {
            sb.append("<ul class=\"notable\">");
            for (String n : notable) sb.append("<li>").append(escape(n)).append("</li>");
            sb.append("</ul>");
        }

        Map<String, Object> perTxn = (Map<String, Object>) d.getOrDefault("per_transaction", Map.of());
        if (!perTxn.isEmpty()) {
            sb.append("<table><thead><tr>")
              .append("<th>Transaction</th><th>Count &Delta;</th><th>Error &Delta;pp</th>")
              .append("<th>Avg RT %</th><th>P95 RT %</th><th>Max RT %</th></tr></thead><tbody>");
            for (Map.Entry<String, Object> e : perTxn.entrySet()) {
                Map<String, Object> row = (Map<String, Object>) e.getValue();
                Object status = row.get("status");
                if ("new".equals(status)) {
                    sb.append("<tr><td>").append(escape(e.getKey())).append("</td>")
                      .append("<td colspan=\"5\" class=\"muted\">new transaction</td></tr>");
                    continue;
                }
                if ("gone".equals(status)) {
                    sb.append("<tr><td>").append(escape(e.getKey())).append("</td>")
                      .append("<td colspan=\"5\" class=\"muted\">missing this run</td></tr>");
                    continue;
                }
                sb.append("<tr>")
                  .append("<td>").append(escape(e.getKey())).append("</td>")
                  .append("<td>").append(row.getOrDefault("count_delta", 0)).append("</td>")
                  .append("<td>").append(tone(asDouble(row.get("error_rate_pp")), 2.0)).append(fmtSigned(row.get("error_rate_pp"), "pp")).append("</span></td>")
                  .append("<td>").append(tone(asDouble(row.get("rt_avg_pct")), 20.0)).append(fmtSigned(row.get("rt_avg_pct"), "%")).append("</span></td>")
                  .append("<td>").append(tone(asDouble(row.get("rt_p95_pct")), 20.0)).append(fmtSigned(row.get("rt_p95_pct"), "%")).append("</span></td>")
                  .append("<td>").append(tone(asDouble(row.get("rt_max_pct")), 20.0)).append(fmtSigned(row.get("rt_max_pct"), "%")).append("</span></td>")
                  .append("</tr>");
            }
            sb.append("</tbody></table>");
        }
        sb.append("</section>");
    }

    private static String tone(double v, double threshold) {
        String cls = Math.abs(v) < threshold ? "delta-neutral"
                : v > 0 ? "delta-worse" : "delta-better";
        return "<span class=\"" + cls + "\">";
    }

    private static String fmtSigned(Object o, String unit) {
        double v = asDouble(o);
        return (v > 0 ? "+" : "") + v + unit;
    }

    private static double asDouble(Object o) {
        if (o instanceof Number n) return n.doubleValue();
        if (o instanceof String s) { try { return Double.parseDouble(s); } catch (Exception e) { return 0; } }
        return 0;
    }

    @SuppressWarnings("unchecked")
    private void renderVerdictBadge(StringBuilder sb, Context ctx) {
        if (ctx.verdict == null || ctx.verdict.isEmpty()) return;
        String level = String.valueOf(ctx.verdict.getOrDefault("level", "INSUFFICIENT_DATA"));
        String cls = "verdict-" + level.toLowerCase().replace('_', '-');
        double conf = asDouble(ctx.verdict.get("production_confidence"));
        double risk = asDouble(ctx.verdict.get("risk_score"));
        sb.append("<section class=\"verdict ").append(cls).append("\">")
          .append("<div class=\"verdict-badge\">").append(escape(level.replace('_', ' '))).append("</div>")
          .append("<div class=\"verdict-body\">")
          .append("<div class=\"verdict-rationale\">").append(escape(String.valueOf(ctx.verdict.getOrDefault("rationale", "")))).append("</div>")
          .append("<div class=\"pill-row\">")
          .append(pill("Production Confidence", conf + "/100"))
          .append(pill("Risk Score", risk + "/100"))
          .append(pill("Recommendation", String.valueOf(ctx.verdict.getOrDefault("deployment_recommendation", ""))))
          .append("</div>");
        List<String> passed = (List<String>) ctx.verdict.getOrDefault("gates_passed", List.of());
        List<String> failed = (List<String>) ctx.verdict.getOrDefault("gates_failed", List.of());
        if (!passed.isEmpty() || !failed.isEmpty()) {
            sb.append("<div class=\"gates\">");
            for (String g : passed) sb.append("<span class=\"gate gate-pass\">&#10003; ").append(escape(g)).append("</span>");
            for (String g : failed) sb.append("<span class=\"gate gate-fail\">&#10007; ").append(escape(g)).append("</span>");
            sb.append("</div>");
        }
        List<String> rollout = (List<String>) ctx.verdict.getOrDefault("rollout_plan", List.of());
        if (!rollout.isEmpty()) {
            sb.append("<h4>Rollout plan</h4><ol>");
            for (String r : rollout) sb.append("<li>").append(escape(r)).append("</li>");
            sb.append("</ol>");
        }
        List<String> rollback = (List<String>) ctx.verdict.getOrDefault("rollback_triggers", List.of());
        if (!rollback.isEmpty()) {
            sb.append("<h4>Rollback triggers</h4><ul>");
            for (String r : rollback) sb.append("<li>").append(escape(r)).append("</li>");
            sb.append("</ul>");
        }
        sb.append("</div></section>");
    }

    private void renderHealthScores(StringBuilder sb, Context ctx) {
        if (ctx.scores == null || ctx.scores.isEmpty()) return;
        sb.append("<section class=\"card\"><h2>Health Scores (0-100)</h2>")
          .append("<div class=\"scores\">");
        String[] keys = {"performance", "infrastructure", "application", "database", "observability",
                "scalability", "reliability", "availability",
                "composite_performance", "release_readiness", "production_confidence"};
        String[] labels = {"Performance", "Infrastructure", "Application", "Database", "Observability",
                "Scalability", "Reliability", "Availability",
                "Composite Perf", "Release Readiness", "Production Confidence"};
        for (int i = 0; i < keys.length; i++) {
            double v = asDouble(ctx.scores.get(keys[i]));
            sb.append(gauge(labels[i], v));
        }
        sb.append("</div></section>");
    }

    private static String gauge(String label, double value) {
        String tone = value >= 80 ? "kpi-ok" : value >= 60 ? "kpi-warn" : "kpi-danger";
        int pct = (int) Math.round(value);
        return "<div class=\"score-gauge " + tone + "\">"
                + "<div class=\"gauge-bar\"><div class=\"gauge-fill\" style=\"width:" + pct + "%\"></div></div>"
                + "<div class=\"gauge-label\">" + escape(label) + "</div>"
                + "<div class=\"gauge-value\">" + pct + "</div>"
                + "</div>";
    }

    @SuppressWarnings("unchecked")
    private void renderFindings(StringBuilder sb, Context ctx) {
        List<Map<String, Object>> fs = ctx.findings;
        if (fs == null || fs.isEmpty()) return;
        sb.append("<section class=\"card\"><h2>Deterministic Findings</h2>")
          .append("<table><thead><tr>")
          .append("<th>Severity</th><th>Rule</th><th>Title</th><th>Confidence</th><th>Evidence</th>")
          .append("</tr></thead><tbody>");
        for (Map<String, Object> f : fs) {
            String sev = String.valueOf(f.getOrDefault("severity", "INFO"));
            String rowCls = switch (sev) {
                case "CRITICAL", "HIGH" -> " class=\"row-danger\"";
                case "MEDIUM" -> " class=\"row-warn\"";
                default -> "";
            };
            sb.append("<tr").append(rowCls).append(">")
              .append("<td>").append(escape(sev)).append("</td>")
              .append("<td><code>").append(escape(String.valueOf(f.get("id")))).append("</code></td>")
              .append("<td>").append(escape(String.valueOf(f.getOrDefault("title", "")))).append("</td>")
              .append("<td>").append(escape(String.format("%.2f", asDouble(f.get("confidence"))))).append("</td>")
              .append("<td class=\"muted\">").append(escape(String.valueOf(f.getOrDefault("evidence", "")))).append("</td>")
              .append("</tr>");
        }
        sb.append("</tbody></table></section>");
    }

    @SuppressWarnings("unchecked")
    private void renderCloudWatch(StringBuilder sb, Context ctx) {
        if (ctx.cloudwatch == null || ctx.cloudwatch.isEmpty()) return;
        Map<String, Object> metrics = (Map<String, Object>) ctx.cloudwatch.getOrDefault("metrics", Map.of());
        List<Map<String, Object>> alarms = (List<Map<String, Object>>) ctx.cloudwatch.getOrDefault("alarms", List.of());
        if (metrics.isEmpty() && alarms.isEmpty()) return;
        sb.append("<section class=\"card\"><h2>AWS CloudWatch</h2>");
        if (!metrics.isEmpty()) {
            sb.append("<h4>Metrics</h4><table><thead><tr><th>Metric</th><th>Points</th></tr></thead><tbody>");
            for (Map.Entry<String, Object> e : metrics.entrySet()) {
                int count = e.getValue() instanceof List<?> l ? l.size() : 0;
                sb.append("<tr><td>").append(escape(e.getKey())).append("</td><td>").append(count).append("</td></tr>");
            }
            sb.append("</tbody></table>");
        }
        if (!alarms.isEmpty()) {
            sb.append("<h4>Alarms</h4><table><thead><tr><th>Name</th><th>State</th><th>Reason</th></tr></thead><tbody>");
            for (Map<String, Object> a : alarms) {
                String state = String.valueOf(a.getOrDefault("state", ""));
                String rowCls = "ALARM".equalsIgnoreCase(state) ? " class=\"row-danger\"" : "";
                sb.append("<tr").append(rowCls).append(">")
                  .append("<td>").append(escape(String.valueOf(a.getOrDefault("name", "")))).append("</td>")
                  .append("<td>").append(escape(state)).append("</td>")
                  .append("<td class=\"muted\">").append(escape(String.valueOf(a.getOrDefault("reason", "")))).append("</td>")
                  .append("</tr>");
            }
            sb.append("</tbody></table>");
        }
        sb.append("</section>");
    }

    @SuppressWarnings("unchecked")
    private void renderBusinessImpact(StringBuilder sb, Context ctx) {
        if (ctx.aiInsights == null || ctx.aiInsights.isEmpty()) return;
        Map<String, Object> bi = (Map<String, Object>) ctx.aiInsights.get("business_impact");
        Map<String, Object> cap = (Map<String, Object>) ctx.aiInsights.get("capacity_estimate");
        if ((bi == null || bi.isEmpty()) && (cap == null || cap.isEmpty())) return;
        sb.append("<section class=\"card\"><h2>Business Impact &amp; Capacity Forecast</h2>")
          .append("<div class=\"pill-row\">");
        if (bi != null) {
            if (bi.get("lost_conversions_est") != null)
                sb.append(pill("Est. lost conversions", String.valueOf(bi.get("lost_conversions_est"))));
            if (bi.get("usd_est") != null)
                sb.append(pill("Est. impact", "$" + bi.get("usd_est")));
        }
        if (cap != null) {
            if (cap.get("peak_supported_tps") != null)
                sb.append(pill("Peak supported TPS", String.valueOf(cap.get("peak_supported_tps"))));
            if (cap.get("cliff_tps") != null)
                sb.append(pill("Cliff TPS", String.valueOf(cap.get("cliff_tps"))));
            if (cap.get("months_headroom") != null)
                sb.append(pill("Headroom (months)", String.valueOf(cap.get("months_headroom"))));
        }
        sb.append("</div>");
        if (bi != null && bi.get("note") != null && !String.valueOf(bi.get("note")).isBlank()) {
            sb.append("<p class=\"muted\">").append(escape(String.valueOf(bi.get("note")))).append("</p>");
        }
        sb.append("</section>");
    }

    private void renderAppendix(StringBuilder sb, Context ctx) {
        sb.append("<section class=\"card appendix\"><h2>Appendix</h2>")
          .append("<div class=\"pill-row\">")
          .append(pill("Test", ctx.testName == null ? "" : ctx.testName))
          .append(pill("Env", ctx.environment == null ? "" : ctx.environment))
          .append(pill("App", ctx.application == null ? "" : ctx.application))
          .append(pill("Started", formatTs(ctx.startMs)))
          .append(pill("Stopped", formatTs(ctx.stopMs)))
          .append("</div>")
          .append("<p class=\"muted\">Raw evidence: local NDJSON, Splunk correlation JSON, O11y JSON, "
                  + "CloudWatch JSON, structured AI insights JSON, and CSV are all saved alongside this "
                  + "report inside the configured Output_Directory.</p>")
          .append("</section>");
    }

    @SuppressWarnings("unchecked")
    private void renderCorrelation(StringBuilder sb, Context ctx) {
        Map<String, Object> corr = ctx.correlation;
        if (corr == null || corr.isEmpty()) return;
        long failureCount = asLong(corr.get("failure_count"), 0);
        long windowSec = asLong(corr.get("window_seconds"), 0);
        List<Map<String, Object>> windows = (List<Map<String, Object>>) corr.getOrDefault("windows", List.of());
        int totalEvents = 0;
        for (Map<String, Object> w : windows) totalEvents += (int) asLong(w.get("event_count"), 0);
        sb.append("<section class=\"card\"><h2>Splunk Log Correlation</h2>")
          .append("<div class=\"pill-row\">")
          .append(pill("Failed samples", Long.toString(failureCount)))
          .append(pill("Window", "\u00B1" + windowSec + "s"))
          .append(pill("Merged windows", Integer.toString(windows.size())))
          .append(pill("Correlated events", Integer.toString(totalEvents)))
          .append("</div>");
        if (totalEvents == 0 && !windows.isEmpty()) {
            sb.append("<p class=\"muted\">No log events found in the correlation windows.</p>");
        }
        sb.append("</section>");
    }

    private void renderO11y(StringBuilder sb, Context ctx) {
        if (ctx.o11yMetrics == null || ctx.o11yMetrics.isEmpty()) return;
        sb.append("<section class=\"card\"><h2>Splunk Observability Cloud Metrics</h2>")
          .append("<table><thead><tr><th>Metric</th><th>Points</th></tr></thead><tbody>");
        for (Map.Entry<String, List<Map<String, Object>>> e : ctx.o11yMetrics.entrySet()) {
            int count = e.getValue() == null ? 0 : e.getValue().size();
            sb.append("<tr><td>").append(escape(e.getKey())).append("</td>")
              .append("<td>").append(count).append("</td></tr>");
        }
        sb.append("</tbody></table></section>");
    }

    private void renderAnalysis(StringBuilder sb, Context ctx) {
        sb.append("<section class=\"card analysis\">")
          .append("<h2>AI Root Cause Analysis</h2>");
        if (ctx.llmProvider != null && !ctx.llmProvider.isBlank()) {
            sb.append("<div class=\"provider\">Provider: <code>").append(escape(ctx.llmProvider))
              .append("</code>");
            if (ctx.llmModel != null && !ctx.llmModel.isBlank()) {
                sb.append(" &middot; Model: <code>").append(escape(ctx.llmModel)).append("</code>");
            }
            sb.append("</div>");
        }
        sb.append("<div class=\"analysis-body\">")
          .append(Markdown.render(ctx.llmAnalysis == null ? "" : ctx.llmAnalysis))
          .append("</div></section>");
    }

    /* --------- v2.0.2 sections --------- */

    private void renderCharts(StringBuilder sb, Context ctx) {
        String waterfall = SvgCharts.waterfall(ctx.aggregate, 12);
        String sankey = SvgCharts.verdictSankey(ctx.verdict);
        String depMap = SvgCharts.dependencyMap(ctx.aggregate);
        if (waterfall.isEmpty() && sankey.isEmpty() && depMap.isEmpty()) return;
        sb.append("<section class=\"card\"><h2>Visual Analytics</h2>")
          .append("<div class=\"svg-grid\">");
        if (!waterfall.isEmpty()) sb.append("<div class=\"svg-box\">").append(waterfall).append("</div>");
        if (!sankey.isEmpty())    sb.append("<div class=\"svg-box\">").append(sankey).append("</div>");
        if (!depMap.isEmpty())    sb.append("<div class=\"svg-box\">").append(depMap).append("</div>");
        sb.append("</div></section>");
    }

    private void renderExternalMetrics(StringBuilder sb, Context ctx) {
        if (ctx.externalMetrics == null || ctx.externalMetrics.isEmpty()) return;
        sb.append("<section class=\"card\"><h2>External Observability Sources</h2>");
        for (Map.Entry<String, Map<String, List<Map<String, Object>>>> be : ctx.externalMetrics.entrySet()) {
            String backend = be.getKey();
            sb.append("<h4>").append(escape(backend.toUpperCase())).append("</h4>")
              .append("<table><thead><tr><th>Query</th><th>Points</th><th>Min</th><th>Avg</th><th>Max</th></tr></thead><tbody>");
            for (Map.Entry<String, List<Map<String, Object>>> q : be.getValue().entrySet()) {
                List<Map<String, Object>> pts = q.getValue();
                int n = pts == null ? 0 : pts.size();
                double min = Double.MAX_VALUE, max = 0, sum = 0;
                if (n > 0) {
                    for (Map<String, Object> p : pts) {
                        double v = asDouble(p.get("value"));
                        if (v < min) min = v;
                        if (v > max) max = v;
                        sum += v;
                    }
                }
                sb.append("<tr><td>").append(escape(q.getKey())).append("</td>")
                  .append("<td>").append(n).append("</td>")
                  .append("<td>").append(n == 0 ? "-" : fmtNum(min)).append("</td>")
                  .append("<td>").append(n == 0 ? "-" : fmtNum(sum / n)).append("</td>")
                  .append("<td>").append(n == 0 ? "-" : fmtNum(max)).append("</td></tr>");
            }
            sb.append("</tbody></table>");
        }
        sb.append("</section>");
    }

    private void renderCapacityForecast(StringBuilder sb, Context ctx) {
        if (ctx.forecast == null || ctx.forecast.isEmpty()) return;
        boolean insufficient = Boolean.TRUE.equals(ctx.forecast.get("insufficient"));
        String verdict = String.valueOf(ctx.forecast.getOrDefault("verdict", ""));
        String cls = switch (verdict) {
            case "OK" -> "verdict-go";
            case "WATCH" -> "verdict-go-with-conditions";
            case "BREACH_SOON", "BREACHED" -> "verdict-no-go";
            default -> "verdict-insufficient-data";
        };
        sb.append("<section class=\"card\"><h2>Capacity Forecast</h2>");
        if (insufficient) {
            sb.append("<p class=\"muted\">").append(escape(String.valueOf(ctx.forecast.get("rationale"))))
              .append(" Snapshots collected: ").append(escape(String.valueOf(ctx.forecast.get("samples"))))
              .append("</p></section>");
            return;
        }
        Object daysP50 = ctx.forecast.get("days_to_breach_p50");
        Object daysP90 = ctx.forecast.get("days_to_breach_p90");
        sb.append("<div class=\"forecast-hero ").append(cls).append("\">")
          .append("<div class=\"forecast-badge\">").append(escape(verdict.replace('_', ' '))).append("</div>")
          .append("<div class=\"forecast-body\">")
          .append("<div class=\"pill-row\">")
          .append(pill("Days to breach (expected)", String.valueOf(daysP50)))
          .append(pill("Days to breach (p90 upper)", String.valueOf(daysP90)))
          .append(pill("Current p95", ctx.forecast.getOrDefault("current_p95_ms", 0) + " ms"))
          .append(pill("SLA", ctx.forecast.getOrDefault("sla_p95_ms", 0) + " ms"))
          .append(pill("Slope", ctx.forecast.getOrDefault("slope_ms_per_day", 0) + " ms/day"))
          .append(pill("Samples", String.valueOf(ctx.forecast.getOrDefault("samples", 0))))
          .append("</div>")
          .append("<p class=\"forecast-rationale\">").append(escape(String.valueOf(ctx.forecast.get("rationale")))).append("</p>")
          .append("</div></div>");
        sb.append("</section>");
    }

    private static String fmtNum(double v) {
        if (Math.abs(v) < 10) return String.format("%.3f", v);
        if (Math.abs(v) < 1000) return String.format("%.1f", v);
        return String.format("%.0f", v);
    }

    /* --------- helpers --------- */

    private static void appendMeta(StringBuilder sb, String k, String v) {
        if (v == null || v.isBlank()) return;
        sb.append("<span><b>").append(escape(k)).append(":</b> ").append(escape(v)).append("</span>");
    }

    private static void kpi(StringBuilder sb, String label, String value, String tone) {
        sb.append("<div class=\"kpi").append(tone == null ? "" : " kpi-" + tone).append("\">")
          .append("<div class=\"kpi-value\">").append(escape(value)).append("</div>")
          .append("<div class=\"kpi-label\">").append(escape(label)).append("</div>")
          .append("</div>");
    }

    private static String pill(String label, String value) {
        return "<span class=\"pill\"><b>" + escape(label) + ":</b> " + escape(value) + "</span>";
    }

    private static long asLong(Object o, long defaultVal) {
        if (o instanceof Number n) return n.longValue();
        if (o instanceof String s) {
            try { return Long.parseLong(s); } catch (Exception e) { return defaultVal; }
        }
        return defaultVal;
    }

    private static String formatTs(long ms) {
        if (ms <= 0) return "";
        return DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss 'UTC'")
                .withZone(ZoneOffset.UTC)
                .format(Instant.ofEpochMilli(ms));
    }

    static String escape(String in) {
        if (in == null) return "";
        return in.replace("&", "&amp;")
                 .replace("<", "&lt;")
                 .replace(">", "&gt;")
                 .replace("\"", "&quot;");
    }

    /* --------- Context object --------- */

    public static class Context {
        final String testName;
        final String environment;
        final String application;
        final long startMs;
        final long stopMs;
        final Map<String, Object> aggregate;
        final Map<String, Object> correlation;
        final Map<String, List<Map<String, Object>>> o11yMetrics;
        final Map<String, Object> cloudwatch;
        final Map<String, Object> scores;
        final Map<String, Object> verdict;
        final List<Map<String, Object>> findings;
        final Map<String, Object> baselineDiff;
        final Map<String, Object> aiInsights;
        final String llmAnalysis;
        final String llmProvider;
        final String llmModel;
        final Map<String, Map<String, List<Map<String, Object>>>> externalMetrics;
        final Map<String, Object> forecast;

        Context(Builder b) {
            this.testName = b.testName;
            this.environment = b.environment;
            this.application = b.application;
            this.startMs = b.startMs;
            this.stopMs = b.stopMs;
            this.aggregate = b.aggregate == null ? new LinkedHashMap<>() : b.aggregate;
            this.correlation = b.correlation == null ? new LinkedHashMap<>() : b.correlation;
            this.o11yMetrics = b.o11yMetrics == null ? Map.of() : b.o11yMetrics;
            this.cloudwatch = b.cloudwatch == null ? new LinkedHashMap<>() : b.cloudwatch;
            this.scores = b.scores == null ? new LinkedHashMap<>() : b.scores;
            this.verdict = b.verdict == null ? new LinkedHashMap<>() : b.verdict;
            this.findings = b.findings == null ? List.of() : b.findings;
            this.baselineDiff = b.baselineDiff;
            this.aiInsights = b.aiInsights == null ? new LinkedHashMap<>() : b.aiInsights;
            this.llmAnalysis = b.llmAnalysis;
            this.llmProvider = b.llmProvider;
            this.llmModel = b.llmModel;
            this.externalMetrics = b.externalMetrics == null ? Map.of() : b.externalMetrics;
            this.forecast = b.forecast == null ? Map.of() : b.forecast;
        }

        public static class Builder {
            private String testName;
            private String environment;
            private String application;
            private long startMs;
            private long stopMs;
            private Map<String, Object> aggregate;
            private Map<String, Object> correlation;
            private Map<String, List<Map<String, Object>>> o11yMetrics;
            private Map<String, Object> cloudwatch;
            private Map<String, Object> scores;
            private Map<String, Object> verdict;
            private List<Map<String, Object>> findings;
            private Map<String, Object> baselineDiff;
            private Map<String, Object> aiInsights;
            private String llmAnalysis;
            private String llmProvider;
            private String llmModel;
            private Map<String, Map<String, List<Map<String, Object>>>> externalMetrics;
            private Map<String, Object> forecast;

            public Builder testName(String v) { this.testName = v; return this; }
            public Builder environment(String v) { this.environment = v; return this; }
            public Builder application(String v) { this.application = v; return this; }
            public Builder startMs(long v) { this.startMs = v; return this; }
            public Builder stopMs(long v) { this.stopMs = v; return this; }
            public Builder aggregate(Map<String, Object> v) { this.aggregate = v; return this; }
            public Builder correlation(Map<String, Object> v) { this.correlation = v; return this; }
            public Builder o11yMetrics(Map<String, List<Map<String, Object>>> v) { this.o11yMetrics = v; return this; }
            public Builder cloudwatch(Map<String, Object> v) { this.cloudwatch = v; return this; }
            public Builder scores(Map<String, Object> v) { this.scores = v; return this; }
            public Builder verdict(Map<String, Object> v) { this.verdict = v; return this; }
            public Builder findings(List<Map<String, Object>> v) { this.findings = v; return this; }
            public Builder baselineDiff(Map<String, Object> v) { this.baselineDiff = v; return this; }
            public Builder aiInsights(Map<String, Object> v) { this.aiInsights = v; return this; }
            public Builder llmAnalysis(String v) { this.llmAnalysis = v; return this; }
            public Builder llmProvider(String v) { this.llmProvider = v; return this; }
            public Builder llmModel(String v) { this.llmModel = v; return this; }
            public Builder externalMetrics(Map<String, Map<String, List<Map<String, Object>>>> v) { this.externalMetrics = v; return this; }
            public Builder forecast(Map<String, Object> v) { this.forecast = v; return this; }
            public Context build() { return new Context(this); }
        }
    }

    /* --------- Embedded CSS --------- */

    private static final String CSS = """
            :root {
              --bg: #0f172a;
              --card: #ffffff;
              --card-alt: #f8fafc;
              --ink: #0f172a;
              --muted: #64748b;
              --line: #e2e8f0;
              --accent: #4f46e5;
              --ok: #10b981;
              --warn: #f59e0b;
              --danger: #ef4444;
              --code-bg: #f1f5f9;
              --shadow: 0 1px 3px rgba(15,23,42,.06), 0 1px 2px rgba(15,23,42,.04);
            }
            * { box-sizing: border-box; }
            body {
              margin: 0;
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, sans-serif;
              color: var(--ink);
              background: #f1f5f9;
              line-height: 1.5;
            }
            header.hero {
              background: linear-gradient(135deg, #1e1b4b 0%, #4f46e5 100%);
              color: #fff;
              padding: 32px 40px 24px;
            }
            header.hero .tag {
              display: inline-block;
              background: rgba(255,255,255,.15);
              padding: 4px 10px;
              border-radius: 999px;
              font-size: 12px;
              letter-spacing: .08em;
              text-transform: uppercase;
              margin-bottom: 12px;
            }
            header.hero h1 { margin: 0 0 12px; font-size: 28px; font-weight: 600; }
            header.hero .meta {
              display: flex; flex-wrap: wrap; gap: 8px 24px;
              font-size: 13px; color: rgba(255,255,255,.85);
            }
            header.hero .meta b { color: #fff; font-weight: 500; }
            section { margin: 24px 40px; }
            section.card {
              background: var(--card);
              border-radius: 12px;
              padding: 20px 24px;
              box-shadow: var(--shadow);
            }
            section.card h2 {
              margin: 0 0 16px; font-size: 16px; font-weight: 600;
              color: var(--muted); text-transform: uppercase; letter-spacing: .06em;
            }
            section.kpis {
              display: grid;
              grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
              gap: 12px;
            }
            .kpi {
              background: var(--card);
              border-radius: 12px;
              padding: 16px 18px;
              box-shadow: var(--shadow);
              border-left: 4px solid var(--accent);
            }
            .kpi-ok { border-left-color: var(--ok); }
            .kpi-warn { border-left-color: var(--warn); }
            .kpi-danger { border-left-color: var(--danger); }
            .kpi-value { font-size: 22px; font-weight: 600; }
            .kpi-label { font-size: 12px; color: var(--muted); margin-top: 2px; }
            table { width: 100%; border-collapse: collapse; font-size: 14px; }
            th, td { padding: 8px 10px; text-align: left; border-bottom: 1px solid var(--line); }
            th { font-weight: 600; color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: .05em; }
            tr.row-danger td:first-child { color: var(--danger); font-weight: 600; }
            .pill-row { display: flex; flex-wrap: wrap; gap: 8px; }
            .pill {
              background: var(--card-alt); border: 1px solid var(--line);
              padding: 6px 12px; border-radius: 999px; font-size: 13px;
            }
            .pill b { color: var(--muted); font-weight: 500; margin-right: 4px; }
            .muted { color: var(--muted); font-size: 13px; margin: 8px 0 0; }
            .analysis .provider { font-size: 12px; color: var(--muted); margin-bottom: 12px; }
            .analysis code { background: var(--code-bg); padding: 1px 6px; border-radius: 4px; font-size: 90%; }
            .analysis-body h1, .analysis-body h2, .analysis-body h3, .analysis-body h4 {
              margin: 18px 0 8px; line-height: 1.3;
            }
            .analysis-body h1 { font-size: 18px; }
            .analysis-body h2 { font-size: 16px; color: var(--accent); }
            .analysis-body h3 { font-size: 14px; }
            .analysis-body ul, .analysis-body ol { padding-left: 22px; margin: 8px 0; }
            .analysis-body li { margin: 4px 0; }
            .analysis-body p { margin: 8px 0; }
            .analysis-body strong { color: var(--ink); }
            footer { text-align: center; color: var(--muted); font-size: 12px; padding: 24px 0 32px; }
            ul.notable { margin: 12px 0; padding-left: 20px; }
            ul.notable li { margin: 3px 0; color: var(--danger); font-weight: 500; }
            .delta-worse { color: var(--danger); font-weight: 600; }
            .delta-better { color: var(--ok); font-weight: 600; }
            .delta-neutral { color: var(--muted); }
            section.verdict { margin: 24px 40px; padding: 24px 28px; border-radius: 16px; color: #fff;
              display: grid; grid-template-columns: minmax(180px, 220px) 1fr; gap: 24px; align-items: start; }
            .verdict-go { background: linear-gradient(135deg, #059669 0%, #10b981 100%); }
            .verdict-go-with-conditions { background: linear-gradient(135deg, #b45309 0%, #f59e0b 100%); }
            .verdict-no-go { background: linear-gradient(135deg, #7f1d1d 0%, #ef4444 100%); }
            .verdict-insufficient-data { background: linear-gradient(135deg, #374151 0%, #6b7280 100%); }
            .verdict-badge { font-size: 32px; font-weight: 700; letter-spacing: .04em; text-align: center;
              padding: 32px 12px; background: rgba(255,255,255,.15); border-radius: 12px; line-height: 1.1; }
            .verdict-body .pill { background: rgba(255,255,255,.2); border-color: rgba(255,255,255,.25); color:#fff; }
            .verdict-body .pill b { color: rgba(255,255,255,.85); }
            .verdict-rationale { font-size: 15px; margin-bottom: 12px; opacity:.95; }
            .verdict-body h4 { font-size: 12px; text-transform: uppercase; letter-spacing: .06em;
              opacity:.85; margin: 14px 0 6px; }
            .verdict-body ol, .verdict-body ul { margin: 6px 0 0; padding-left: 22px; }
            .gates { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 10px; }
            .gate { font-size: 12px; padding: 4px 10px; border-radius: 999px;
              background: rgba(255,255,255,.15); }
            .gate-pass { background: rgba(16,185,129,.35); }
            .gate-fail { background: rgba(239,68,68,.35); }
            .scores { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 10px; }
            .score-gauge { display: grid; grid-template-columns: 1fr auto; gap: 4px 12px;
              align-items: center; padding: 10px 14px; border-radius: 8px;
              background: var(--card-alt); border-left: 3px solid var(--accent); }
            .score-gauge.kpi-ok { border-left-color: var(--ok); }
            .score-gauge.kpi-warn { border-left-color: var(--warn); }
            .score-gauge.kpi-danger { border-left-color: var(--danger); }
            .gauge-label { font-size: 12px; color: var(--muted); grid-column: 1; grid-row: 2; }
            .gauge-value { font-size: 18px; font-weight: 600; grid-column: 2; grid-row: 1 / 3; align-self: center; }
            .gauge-bar { grid-column: 1; grid-row: 1; height: 6px; background: var(--line); border-radius: 3px; overflow: hidden; }
            .gauge-fill { height: 100%; background: var(--accent); }
            .score-gauge.kpi-ok .gauge-fill { background: var(--ok); }
            .score-gauge.kpi-warn .gauge-fill { background: var(--warn); }
            .score-gauge.kpi-danger .gauge-fill { background: var(--danger); }
            tr.row-warn td:first-child { color: var(--warn); font-weight: 600; }
            section.appendix { background: var(--card-alt); }
            .svg-grid { display: grid; grid-template-columns: 1fr; gap: 20px; }
            @media (min-width: 1200px) { .svg-grid { grid-template-columns: 1fr 1fr; } }
            .svg-box { background: var(--card-alt); border-radius: 8px; padding: 12px; overflow-x: auto; }
            .svg-box svg { width: 100%; height: auto; display: block; }
            .forecast-hero { display: grid; grid-template-columns: minmax(160px, 200px) 1fr; gap: 16px;
                             padding: 20px; border-radius: 12px; color: #fff; align-items: start; }
            .forecast-badge { font-size: 22px; font-weight: 700; letter-spacing: .04em; text-align: center;
                              padding: 20px 8px; background: rgba(255,255,255,.15); border-radius: 8px; }
            .forecast-body .pill { background: rgba(255,255,255,.2); border-color: rgba(255,255,255,.25); color:#fff; }
            .forecast-body .pill b { color: rgba(255,255,255,.85); }
            .forecast-rationale { font-size: 14px; margin-top: 10px; opacity:.95; }
            """;
}
